server:
port: 8787

spring:
datasource:
url: jdbc:mysql://training-demo.c9n5h8zmwxv7.us-east-2.rds.amazonaws.com:3306/myprofolio

username: admin
password: testing1234
jpa:
hibernate:
ddl-auto: update

logging:
level:
com:
ventail: DEBUG